name: Python package

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=20 --max-line-length=300 --statistics
      - name: Test the parser
        run: |
          python3 -m unittest discover -s Tests/test_parser  -p 'test_*.py'
      - name: Test the knapsack implementation
        run: |
          python3 -m unittest discover -s Tests/test_knapsack  -p 'test_*.py'
      - name: Test the tabu search implementation
        run: |
          echo "Tabu Search tests not implemented yet"